### ISSUE TITLE
Visual Studio 2017

### ISSUE THREAD

**Issue by JStika** [fairmat/DotNet.Highcharts#2]
Hi,

I cannot run, debug with Visual Studio 2017.
Any solution?

**Comment by weltall** [comment]
Visual Studio 2017 seems to have removed by default mvc3 projects support (which is what the samples part uses)
You can still use the library fine as the tests are not essential to use the library.
One solution might be to upgrade the samples project to mvc4 (maybe as explained here http://go.microsoft.com/fwlink/?LinkID=317645 )

**Comment by weltall** [comment]
As of the last merge this is solved so closing.
