### ISSUE TITLE
dotnet core support

### ISSUE THREAD

**Issue by Juslwk** [fairmat/DotNet.Highcharts#3]
Hi,
possible to use with .net core??
thank you.

**Comment by weltall** [comment]
As is the library is built for .net framework.

As a quick test i tried dropping the sources in a .net standard 2 empty project and it almost entirely built (except some minor interfaces which aren't strictly needed)

So, probably you can adapt it to your own use, but patches are well accepted as well for adding support while keeping support for the current applications using the library.

**Comment by CareATC** [comment]
I can confirm that it works with .Net Core 1.1+. We're currently using it with a .Net Core 2.1 project without any issues..

**Comment by lahma** [comment]
I've submitted [a PR](https://github.com/fairmat/DotNet.Highcharts/pull/5) to address this issue.
